@php $navReportsActiveClass = 'active mm-active'; @endphp
@extends('accountant.layouts.app')

@section('content')
<div class="main-content">
    <div class="page-content">
        <div class="container-fluid">
            <div class="page-content-wrapper bg-white p-30 radius-20">

                {{-- Page Title & Breadcrumb --}}
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box d-sm-flex align-items-center justify-content-between border-bottom mb-20">
                            <div class="page-title-left">
                                <h3 class="mb-sm-0">{{ __('Financial Reports') }}</h3>
                            </div>
                            <div class="page-title-right">
                                <ol class="breadcrumb mb-0">
                                    <li class="breadcrumb-item"><a href="{{ route('accountant.dashboard') }}">{{ __('Dashboard') }}</a></li>
                                    <li class="breadcrumb-item active">{{ __('Financial Reports') }}</li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>

                {{-- Action Button --}}
                <div class="row mb-3">
                    <div class="col-12 d-flex justify-content-end">
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#generateModal">
                            <i class="ri-file-chart-line me-1"></i> {{ __('Generate Report') }}
                        </button>
                    </div>
                </div>

                {{-- DataTable --}}
                <div class="row">
                    <div class="col-12">
                        <div class="table-responsive">
                            <table id="reportsTable" class="table table-bordered table-striped align-middle w-100">
                                <thead class="table-light">
                                    <tr>
                                        <th>{{ __('SL') }}</th>
                                        <th>{{ __('Title') }}</th>
                                        <th>{{ __('Report Type') }}</th>
                                        <th>{{ __('Period') }}</th>
                                        <th>{{ __('Status') }}</th>
                                        <th>{{ __('Shared With Shareholders') }}</th>
                                        <th>{{ __('Generated By') }}</th>
                                        <th>{{ __('Created') }}</th>
                                        <th>{{ __('Actions') }}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php
                                        $reportTypeLabels = [
                                            1 => 'Weekly',
                                            2 => 'Monthly',
                                            3 => 'Quarterly',
                                            4 => 'Annual',
                                            5 => 'Custom',
                                        ];
                                    @endphp
                                    @foreach($reports as $index => $r)
                                    <tr>
                                        <td>{{ $reports->firstItem() + $index }}</td>
                                        <td>{{ $r->title }}</td>
                                        <td>{{ $reportTypeLabels[$r->report_type] ?? '—' }}</td>
                                        <td>
                                            {{ \Carbon\Carbon::parse($r->period_start)->format('d M Y') }}
                                            &ndash;
                                            {{ \Carbon\Carbon::parse($r->period_end)->format('d M Y') }}
                                        </td>
                                        <td>
                                            @if($r->status == 1)
                                                <span class="badge bg-secondary">{{ __('Draft') }}</span>
                                            @elseif($r->status == 2)
                                                <span class="badge bg-success">{{ __('Published') }}</span>
                                            @else
                                                <span class="badge bg-secondary">{{ __('Draft') }}</span>
                                            @endif
                                        </td>
                                        <td>
                                            @if($r->shared_with_shareholders)
                                                <span class="badge bg-success">{{ __('Yes') }}</span>
                                            @else
                                                <span class="badge bg-secondary">{{ __('No') }}</span>
                                            @endif
                                        </td>
                                        <td>{{ $r->generatedBy->name ?? '—' }}</td>
                                        <td>{{ $r->created_at->format('d M Y') }}</td>
                                        <td>
                                            <div class="d-inline-flex gap-1 flex-wrap">
                                                <a href="{{ route('accountant.reports.show', $r) }}"
                                                   class="btn btn-sm btn-outline-primary"
                                                   title="{{ __('View') }}">
                                                    <i class="ri-eye-line"></i>
                                                </a>
                                                <a href="{{ route('accountant.reports.print', $r) }}"
                                                   class="btn btn-sm btn-outline-secondary"
                                                   title="{{ __('Print') }}" target="_blank">
                                                    <i class="ri-printer-line"></i>
                                                </a>
                                                <a href="{{ route('accountant.reports.export-csv', $r) }}"
                                                   class="btn btn-sm btn-outline-info"
                                                   title="{{ __('Export CSV') }}">
                                                    <i class="ri-file-download-line"></i>
                                                </a>
                                                @if(!$r->shared_with_shareholders)
                                                <button type="button"
                                                        class="btn btn-sm btn-outline-success report-share-btn"
                                                        data-url="{{ route('accountant.reports.share', $r) }}"
                                                        title="{{ __('Share with Shareholders') }}">
                                                    <i class="ri-share-line"></i>
                                                </button>
                                                @endif
                                                <button type="button"
                                                        class="btn btn-sm btn-outline-danger report-delete-btn"
                                                        data-url="{{ route('accountant.reports.destroy', $r) }}"
                                                        title="{{ __('Delete') }}">
                                                    <i class="ri-delete-bin-line"></i>
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="mt-3">
                            {{ $reports->links() }}
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

{{-- Generate Report Modal --}}
<div class="modal fade" id="generateModal" tabindex="-1" aria-labelledby="generateModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="generateModalLabel">{{ __('Generate Report') }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{{ __('Close') }}"></button>
            </div>
            <form action="{{ route('accountant.reports.generate') }}" method="POST" class="ajax" data-handler="reportShowMessage">
                @csrf
                <div class="modal-body">
                    <div class="row g-3">
                        <div class="col-12">
                            <label class="form-label">{{ __('Report Title') }} <span class="text-danger">*</span></label>
                            <input type="text" name="title" class="form-control" required placeholder="{{ __('Enter report title') }}">
                        </div>
                        <div class="col-md-6">
                            <label class="form-label">{{ __('Report Type') }} <span class="text-danger">*</span></label>
                            <select name="report_type" class="form-select" required>
                                <option value="">{{ __('Select Type') }}</option>
                                <option value="1">{{ __('Weekly') }}</option>
                                <option value="2">{{ __('Monthly') }}</option>
                                <option value="3">{{ __('Quarterly') }}</option>
                                <option value="4">{{ __('Annual') }}</option>
                                <option value="5">{{ __('Custom') }}</option>
                            </select>
                        </div>
                        <div class="col-md-3">
                            <label class="form-label">{{ __('Period Start') }} <span class="text-danger">*</span></label>
                            <input type="date" name="period_start" class="form-control" required>
                        </div>
                        <div class="col-md-3">
                            <label class="form-label">{{ __('Period End') }} <span class="text-danger">*</span></label>
                            <input type="date" name="period_end" class="form-control" required>
                        </div>
                        <div class="col-12">
                            <label class="form-label">{{ __('Notes') }}</label>
                            <textarea name="notes" class="form-control" rows="3" placeholder="{{ __('Optional notes about this report...') }}"></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{ __('Cancel') }}</button>
                    <button type="submit" class="btn btn-primary">
                        <i class="ri-file-chart-line me-1"></i> {{ __('Generate') }}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@push('style')
    @include('common.layouts.datatable-style')
@endpush

@push('script')
    @include('common.layouts.datatable-script')
    <script src="{{ asset('assets/js/custom/accountant-reports.js') }}"></script>
@endpush
