<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $report->title }} - Financial Report</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 14px;
            color: #212529;
        }
        .report-header {
            border-bottom: 3px solid #0d6efd;
            padding-bottom: 16px;
            margin-bottom: 24px;
        }
        .report-header h1 {
            font-size: 20px;
            font-weight: 700;
            color: #0d6efd;
            letter-spacing: 0.5px;
        }
        .stat-box {
            border: 1px solid #dee2e6;
            border-radius: 6px;
            padding: 16px;
            text-align: center;
        }
        .stat-box .label {
            font-size: 12px;
            color: #6c757d;
            margin-bottom: 4px;
        }
        .stat-box .value {
            font-size: 22px;
            font-weight: 700;
        }
        table thead th {
            background-color: #f8f9fa;
        }
        @media print {
            .d-print-none { display: none !important; }
            body { margin: 0; }
            .container { max-width: 100% !important; width: 100% !important; }
        }
    </style>
</head>
<body>
    <div class="container py-4">

        {{-- Print Button --}}
        <div class="d-print-none mb-3 text-end">
            <button onclick="window.print()" class="btn btn-primary">
                Print
            </button>
        </div>

        {{-- Report Header --}}
        <div class="report-header text-center">
            <h1>JINJA CONSOLIDATED PROPERTIES</h1>
            <h2 class="fs-5 fw-bold text-dark">FINANCIAL REPORT</h2>
        </div>

        {{-- Report Metadata --}}
        @php
            $reportTypeLabels = [
                1 => 'Weekly', 2 => 'Monthly', 3 => 'Quarterly', 4 => 'Annual', 5 => 'Custom',
            ];
            $data = $report->report_data ?? [];
        @endphp

        <div class="row mb-4">
            <div class="col-12">
                <table class="table table-bordered table-sm">
                    <tbody>
                        <tr>
                            <th style="width:25%">Report Title</th>
                            <td>{{ $report->title }}</td>
                            <th style="width:25%">Report Type</th>
                            <td>{{ $reportTypeLabels[$report->report_type] ?? '—' }}</td>
                        </tr>
                        <tr>
                            <th>Period</th>
                            <td>
                                {{ \Carbon\Carbon::parse($report->period_start)->format('d M Y') }}
                                &ndash;
                                {{ \Carbon\Carbon::parse($report->period_end)->format('d M Y') }}
                            </td>
                            <th>Generated Date</th>
                            <td>{{ $report->created_at->format('d M Y H:i') }}</td>
                        </tr>
                        <tr>
                            <th>Generated By</th>
                            <td>{{ $report->generatedBy->name ?? '—' }}</td>
                            <th>Status</th>
                            <td>{{ $report->status == 2 ? 'Published' : 'Draft' }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        {{-- Summary Row --}}
        <h5 class="fw-bold mb-3 border-bottom pb-2">Financial Summary</h5>
        <div class="row mb-4">
            <div class="col-md-4 mb-3">
                <div class="stat-box">
                    <div class="label">Total Collections</div>
                    <div class="value text-success">{{ number_format($data['total_collections'] ?? 0) }}</div>
                </div>
            </div>
            <div class="col-md-4 mb-3">
                <div class="stat-box">
                    <div class="label">Total Expenses</div>
                    <div class="value text-danger">{{ number_format($data['total_expenses'] ?? 0) }}</div>
                </div>
            </div>
            <div class="col-md-4 mb-3">
                <div class="stat-box">
                    <div class="label">Net Income</div>
                    <div class="value {{ ($data['net_income'] ?? 0) >= 0 ? 'text-primary' : 'text-danger' }}">
                        {{ number_format($data['net_income'] ?? 0) }}
                    </div>
                </div>
            </div>
        </div>

        {{-- Collections by Payment Method --}}
        <div class="row mb-4">
            <div class="col-md-6 mb-4">
                <h6 class="fw-bold mb-2">Collections by Payment Method</h6>
                <table class="table table-bordered table-sm">
                    <thead>
                        <tr>
                            <th>Method</th>
                            <th class="text-end">Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($data['collections_by_method'] ?? [] as $method => $amount)
                        <tr>
                            <td>{{ ucfirst($method) }}</td>
                            <td class="text-end">{{ number_format($amount) }}</td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="2" class="text-center text-muted">No data available</td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>

            {{-- Collections by Property --}}
            <div class="col-md-6 mb-4">
                <h6 class="fw-bold mb-2">Collections by Property</h6>
                <table class="table table-bordered table-sm">
                    <thead>
                        <tr>
                            <th>Property ID</th>
                            <th class="text-end">Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($data['collections_by_property'] ?? [] as $propertyId => $amount)
                        <tr>
                            <td>{{ $propertyId }}</td>
                            <td class="text-end">{{ number_format($amount) }}</td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="2" class="text-center text-muted">No data available</td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>

        {{-- Expenses by Category --}}
        <h6 class="fw-bold mb-2">Expenses by Category</h6>
        <table class="table table-bordered table-sm mb-4">
            <thead>
                <tr>
                    <th>Category</th>
                    <th class="text-end">Amount</th>
                </tr>
            </thead>
            <tbody>
                @forelse($data['expenses_by_category'] ?? [] as $category => $amount)
                <tr>
                    <td>{{ ucfirst(str_replace('_', ' ', $category)) }}</td>
                    <td class="text-end">{{ number_format($amount) }}</td>
                </tr>
                @empty
                <tr>
                    <td colspan="2" class="text-center text-muted">No expense data available</td>
                </tr>
                @endforelse
            </tbody>
        </table>

        <div class="text-center text-muted mt-5" style="font-size:12px; border-top:1px solid #dee2e6; padding-top:12px;">
            Printed on {{ now()->format('d M Y H:i') }} &mdash; Jinja Consolidated Properties Ltd.
        </div>
    </div>
</body>
</html>
