@php $navReportsActiveClass = 'active mm-active'; @endphp
@extends('accountant.layouts.app')

@section('content')
<div class="main-content">
    <div class="page-content">
        <div class="container-fluid">
            <div class="page-content-wrapper bg-white p-30 radius-20">

                {{-- Page Title & Breadcrumb --}}
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box d-sm-flex align-items-center justify-content-between border-bottom mb-20">
                            <div class="page-title-left">
                                <h3 class="mb-sm-0">{{ __('Report Detail') }}</h3>
                            </div>
                            <div class="page-title-right">
                                <ol class="breadcrumb mb-0">
                                    <li class="breadcrumb-item"><a href="{{ route('accountant.dashboard') }}">{{ __('Dashboard') }}</a></li>
                                    <li class="breadcrumb-item"><a href="{{ route('accountant.reports.index') }}">{{ __('Financial Reports') }}</a></li>
                                    <li class="breadcrumb-item active">{{ __('Report Detail') }}</li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>

                @php
                    $reportTypeLabels = [
                        1 => 'Weekly', 2 => 'Monthly', 3 => 'Quarterly', 4 => 'Annual', 5 => 'Custom',
                    ];
                    $data = $report->report_data ?? [];
                @endphp

                {{-- Report Header Card --}}
                <div class="row mb-4">
                    <div class="col-12">
                        <div class="card border shadow-sm">
                            <div class="card-body">
                                <div class="row align-items-center">
                                    <div class="col-md-8">
                                        <h4 class="mb-1">{{ $report->title }}</h4>
                                        <p class="text-muted mb-1">
                                            <i class="ri-file-chart-line me-1"></i>
                                            {{ $reportTypeLabels[$report->report_type] ?? '—' }}
                                            &nbsp;&bull;&nbsp;
                                            <i class="ri-calendar-line me-1"></i>
                                            {{ \Carbon\Carbon::parse($report->period_start)->format('d M Y') }}
                                            &ndash;
                                            {{ \Carbon\Carbon::parse($report->period_end)->format('d M Y') }}
                                        </p>
                                        <p class="text-muted mb-0">
                                            <i class="ri-user-line me-1"></i>
                                            {{ __('Generated by') }}: <strong>{{ $report->generatedBy->name ?? '—' }}</strong>
                                            &nbsp;&bull;&nbsp;
                                            {{ $report->created_at->format('d M Y H:i') }}
                                        </p>
                                    </div>
                                    <div class="col-md-4 text-md-end mt-3 mt-md-0">
                                        @if($report->status == 2)
                                            <span class="badge bg-success fs-6 px-3 py-2">{{ __('Published') }}</span>
                                        @else
                                            <span class="badge bg-secondary fs-6 px-3 py-2">{{ __('Draft') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {{-- Summary Row --}}
                <div class="row mb-4">
                    <div class="col-md-4 mb-3">
                        <div class="card border text-center h-100">
                            <div class="card-body">
                                <p class="text-muted mb-1">{{ __('Total Collections') }}</p>
                                <h3 class="text-success mb-0">
                                    {{ number_format($data['total_collections'] ?? 0) }}
                                </h3>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3">
                        <div class="card border text-center h-100">
                            <div class="card-body">
                                <p class="text-muted mb-1">{{ __('Total Expenses') }}</p>
                                <h3 class="text-danger mb-0">
                                    {{ number_format($data['total_expenses'] ?? 0) }}
                                </h3>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3">
                        <div class="card border text-center h-100">
                            <div class="card-body">
                                <p class="text-muted mb-1">{{ __('Net Income') }}</p>
                                <h3 class="mb-0 {{ ($data['net_income'] ?? 0) >= 0 ? 'text-primary' : 'text-danger' }}">
                                    {{ number_format($data['net_income'] ?? 0) }}
                                </h3>
                            </div>
                        </div>
                    </div>
                </div>

                {{-- Collections by Payment Method --}}
                <div class="row mb-4">
                    <div class="col-md-6 mb-4">
                        <div class="card border h-100">
                            <div class="card-header bg-light">
                                <h6 class="mb-0"><i class="ri-bank-card-line me-1"></i> {{ __('Collections by Payment Method') }}</h6>
                            </div>
                            <div class="card-body p-0">
                                <div class="table-responsive">
                                    <table class="table table-sm table-striped mb-0">
                                        <thead class="table-light">
                                            <tr>
                                                <th>{{ __('Method') }}</th>
                                                <th class="text-end">{{ __('Amount') }}</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @forelse($data['collections_by_method'] ?? [] as $method => $amount)
                                            <tr>
                                                <td>{{ ucfirst($method) }}</td>
                                                <td class="text-end">{{ number_format($amount) }}</td>
                                            </tr>
                                            @empty
                                            <tr>
                                                <td colspan="2" class="text-center text-muted py-3">{{ __('No data available') }}</td>
                                            </tr>
                                            @endforelse
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>

                    {{-- Collections by Property --}}
                    <div class="col-md-6 mb-4">
                        <div class="card border h-100">
                            <div class="card-header bg-light">
                                <h6 class="mb-0"><i class="ri-building-line me-1"></i> {{ __('Collections by Property') }}</h6>
                            </div>
                            <div class="card-body p-0">
                                <div class="table-responsive">
                                    <table class="table table-sm table-striped mb-0">
                                        <thead class="table-light">
                                            <tr>
                                                <th>{{ __('Property ID') }}</th>
                                                <th class="text-end">{{ __('Amount') }}</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @forelse($data['collections_by_property'] ?? [] as $propertyId => $amount)
                                            <tr>
                                                <td>{{ $propertyId }}</td>
                                                <td class="text-end">{{ number_format($amount) }}</td>
                                            </tr>
                                            @empty
                                            <tr>
                                                <td colspan="2" class="text-center text-muted py-3">{{ __('No data available') }}</td>
                                            </tr>
                                            @endforelse
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {{-- Expenses by Category --}}
                <div class="row mb-4">
                    <div class="col-12">
                        <div class="card border">
                            <div class="card-header bg-light">
                                <h6 class="mb-0"><i class="ri-receipt-line me-1"></i> {{ __('Expenses by Category') }}</h6>
                            </div>
                            <div class="card-body p-0">
                                <div class="table-responsive">
                                    <table class="table table-sm table-striped mb-0">
                                        <thead class="table-light">
                                            <tr>
                                                <th>{{ __('Category') }}</th>
                                                <th class="text-end">{{ __('Amount') }}</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @forelse($data['expenses_by_category'] ?? [] as $category => $amount)
                                            <tr>
                                                <td>{{ ucfirst(str_replace('_', ' ', $category)) }}</td>
                                                <td class="text-end">{{ number_format($amount) }}</td>
                                            </tr>
                                            @empty
                                            <tr>
                                                <td colspan="2" class="text-center text-muted py-3">{{ __('No expense data available') }}</td>
                                            </tr>
                                            @endforelse
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {{-- Action Buttons --}}
                <div class="row">
                    <div class="col-12 d-flex gap-2 flex-wrap">
                        <a href="{{ route('accountant.reports.print', $report) }}"
                           class="btn btn-outline-secondary" target="_blank">
                            <i class="ri-printer-line me-1"></i> {{ __('Print') }}
                        </a>
                        <a href="{{ route('accountant.reports.export-csv', $report) }}"
                           class="btn btn-outline-info">
                            <i class="ri-file-download-line me-1"></i> {{ __('Export CSV') }}
                        </a>
                        @if(!$report->shared_with_shareholders)
                        <button type="button"
                                class="btn btn-outline-success report-share-btn"
                                data-url="{{ route('accountant.reports.share', $report) }}">
                            <i class="ri-share-line me-1"></i> {{ __('Share with Shareholders') }}
                        </button>
                        @endif
                        <a href="{{ route('accountant.reports.index') }}" class="btn btn-outline-dark">
                            <i class="ri-arrow-left-line me-1"></i> {{ __('Back to List') }}
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
@endsection

@push('script')
    <script src="{{ asset('assets/js/custom/accountant-reports.js') }}"></script>
@endpush
